### ISSUE TITLE
DatePicker throwing "Invalid JSON" Exception

### ISSUE THREAD

**Issue by rogvc** [BlazorFluentUI/BlazorFluentUI#301] opened 2021-04-29 16:28 UTC
I have two `DatePickers` bound to two distinct `DateTime?` objects that are not null. When I click on a picker right after having clicked the other, I get the following exception:  

```
Unhandled Exception:
blazor.webassembly.js:1 System.Text.Json.JsonException: Invalid JSON
blazor.webassembly.js:1 at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
blazor.webassembly.js:1 at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS(String argsJson)
```

Here's a link to a video of the issue in action:

https://user-images.githubusercontent.com/29260401/116585057-3bd13980-a8d5-11eb-8d41-c2397d0a5b18.mov

Here's the code:

```
<DatePicker Label="Photograph Date:" Placeholder="Pick the exact photograph date..." AllowTextInput=@false @bind-Value=@Specifics.PhotographDate />

<DatePicker Label="Sample Date:" Placeholder="Pick the exact sample date..." AllowTextInput=@false @bind-Value=@Specifics.SampleDate />
```

**Comment by rogvc** [comment] 2021-04-29 16:42
Ok, the error only shows up if I don't pick a date in the callout and then click on another DatePicker.  I don't know if that helps, but that's what I've been able to narrow it down to.

**Comment by limefrogyank** [comment] 2021-04-29 16:48
I'm taking a look now.

**Comment by limefrogyank** [comment] 2021-04-29 19:52
I think my PR fixes the breaking error, but it's now highlighting another flaw where the callout that was originally dismissed reopens.  It's not as bad as before, but something we still to fix.

**Comment by vnbaaij** [comment] 2021-04-30 13:08
Still seeing this error after meging in #302...

**Comment by rogvc** [comment] 2021-05-03 14:04
What is the underlying issue that is causing the error? I'm wondering if there's a workaround for the issue.

**Comment by vnbaaij** [comment] 2021-05-11 07:54
I have been looking at this but have not found a solution yet. It seem though that the app recovers from the error gracefuly. 

The error is being caused by the Callout component (more specifically the CalloutContent component) that is being used to show the calendars but also for example the list in a dropdown. So you can reproduce the arrow in the online demo at https://www.blazorfluentui.net/DatePickerPage by using the dropdown for the first day of the week and the DatePicker below by making sure the dropdown actually display above the component and click on the Datpicker while the dropdown in open. It gives a lot of (the same) erros, but you can still select a date and it gets bound as well.

I'll try to dig a bit deepre but don't get your hopes up too much. This is a though one to crack, I'm afraid.

**Comment by rogvc** [comment] 2021-05-11 12:43
That's ok. I'm using the BlazorFluentUI Nuget package to have access to these components, so is there a way I can wrap these exceptions in a try/catch? 

I'm fine with them being thrown and letting the component sort itself out, but the exceptions showing up in the console are a little frustrating.

**Comment by vnbaaij** [comment] 2021-05-11 12:48
I was just about to post an update. When I'm running this on my local environment (which is running the Blazor Server version), it doesn't recover. I have to refresh the page to get the SignalR connection running again. The demo site I referred to earlier is running on Blazor WebAssembly so it will recover (there is no SignalR connection that gets disconnected).

You cannot capture the error in a try/catch unfortunately 

Digging deeper...

**Comment by vnbaaij** [comment] 2021-05-11 21:35
Re-enabling the `await OnDismiss.InvokeAsync(null);` line in the FocusHandler method seems to resolve most occurences of the error. 

Getting closer...

**Comment by vnbaaij** [comment] 2021-05-12 09:13
Did some moere testing with this change. Think it solves 99.5% of the occurrences. Closing it with the next commit.

**Closed** 2021-05-12 09:15 UTC
