### ISSUE TITLE
Sometime Dropdown list Not Hiding

### ISSUE THREAD

**Issue by avap90** [BlazorFluentUI/BlazorFluentUI#399] opened 2021-10-04 13:08 UTC
Webassemble sometime Dropdown List or Item&List User Single or Multiple choice.

and other Demo click. but never hiding dropdown list.Just Opened anywhere...

and 

Utility Menu click Text..Show additional Code but..nothing...

![image](https://user-images.githubusercontent.com/16488571/135856701-6903b435-6916-48e4-af48-7f9e7fb95913.png)

**Look.. This is Server Version ...
https://blazorfluentui.azurewebsites.net/labelPage
Drop Down list never hiding....**

![image](https://user-images.githubusercontent.com/16488571/135879445-78a5b84e-dea0-4cc5-9398-b5b08789d047.png)

![image](https://user-images.githubusercontent.com/16488571/135879461-00977b90-1145-400c-883e-555f9c39696a.png)

**Comment by vnbaaij** [comment] 2021-10-04 14:48
Have not seen dropdown list not disappearing issue. 

About the other problem, see #382

**Comment by avap90** [comment] 2021-10-04 15:29
> Have not seen dropdown list not disappearing issue.
> 
> About the other problem, see #382

I update comment.. look... Drop down never hiding...

**Comment by vnbaaij** [comment] 2021-10-05 10:04
Not able to reproduce. Think it is a local browser issue. Otherwise a lot more people would have mentioned.
Closing this

**Closed by vnbaaij** 2021-10-05 10:04 UTC
