### ISSUE TITLE
Control icons often fail to load until 2nd time page refresh

### ISSUE THREAD

**Issue by debrba** [BlazorFluentUI/BlazorFluentUI#340] opened 2021-07-01 19:04 UTC
Control icons often fail to load until 2nd time page refresh. See screenshot below.
![BlazorControlIconsError](https://user-images.githubusercontent.com/84942941/124176838-11d2f980-da75-11eb-839e-1993732d3495.png)

**Comment by vnbaaij** [comment] 2021-07-01 21:39
Duplicate of #237

**Closed by vnbaaij** 2021-07-01 21:39 UTC
