### ISSUE TITLE
RichTextEditor / TextField inside the Panel : quill.js:216 addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by sowsan** [BlazorFluentUI/BlazorFluentUI#133] opened 2020-05-06 23:32 UTC
When I type in RichTextEditor/TextField it is not displaying and seeing the below error in the console

![image](https://user-images.githubusercontent.com/11544153/81238445-1bc3ae80-8fd0-11ea-839d-8ce86395a1b4.png)

getting bunch of below errors as well,
![image](https://user-images.githubusercontent.com/11544153/81238762-dc499200-8fd0-11ea-9627-bb47ab48b04e.png)

When I type anything in the textbox/richtext control it is throwing the below errors
![image](https://user-images.githubusercontent.com/11544153/81320673-8ec83600-905f-11ea-8889-5725f712f8cf.png)

Version : 
`  <PackageReference Include="BlazorFabric.RichTextEditor" Version="2.2.0" />`

Using the rich-text editor within a panel. Its working outside the panel.

```
<Panel IsOpen=@_isNotePanelOpen
       OnDismiss=@(() => _isNotePanelOpen = !_isNotePanelOpen)
       Type=@PanelType.Medium
       IsLightDismiss="true"
       HeaderText="Test Header">
    <RichTextEditor @bind-RichText="@Notes" ReadOnly="false" />
    <br />
    <PrimaryButton Text="Save"  />
</Panel>
```

**Comment by sowsan** [comment] 2020-05-07 19:03
I think the issue could be reported here, https://github.com/BlazorFluentUI/BlazorFluentUI/issues/119, how can I get the fix given that i am using 2.2.0

**Comment by sowsan** [comment] 2020-05-07 19:17
Between same issue with the richtexteditor in the dialogue component.

**Comment by Eweol** [comment] 2020-05-07 21:54
@sowsan Lee maybe you can Deploy a new version 3.0.1 or 3.1 with bug fixes?

**Comment by limefrogyank** [comment] 2020-05-07 22:59
3.0.1 is available.  I know there's a lot to change in your code to support it, but Blazor is an evolving technology and everyone makes mistakes 😉

As for this RichTextEditor component... feel free to use it as-is.  But it was intended as a demonstration.  You can use it to learn how to add your own buttons and interact with quilljs.  There are so many different ways people want to use a rich text editor and maintaining one would be a huge burden, so I left it simple.

I used this tutorial to help understand how quilljs worked:  https://quilljs.com/guides/cloning-medium-with-parchment/

**Comment by limefrogyank** [comment] 2020-05-07 23:12
FYI, the NextParent console messages are not errors.  They are console.log statements I forgot to take out when tracking some bugs.  I'll try to remember to remove those in the next release.

The quill errors are hopefully fixed with the newer version though.

**Comment by sowsan** [comment] 2020-05-07 23:54
Thanks for the clarification and detail @limefrogyank . Thanks @Eweol .

I will try 3.0.1. At this point, I am looking for this to work with the panel control. An input/textfield should be good enough for my need.

**Comment by sowsan** [comment] 2020-05-08 00:17
I just tested the demo version available in this repo (with the assumption that is the latest :) )

Getting the below error in the Panel Control whenever I start to type anything.

![image](https://user-images.githubusercontent.com/11544153/81356660-b2ab6c00-909f-11ea-8b50-b0eecc7bd27b.png)

Here is the code I added in the panelpage

<Panel IsOpen=@lightDismissPanelOpen
       OnDismiss=@(() => lightDismissPanelOpen = !lightDismissPanelOpen)
       Type=@PanelType.Medium
       IsLightDismiss="true"
       HeaderText="Light Dismiss Panel">
    <p>
        This is a light dismiss panel...
        <TextField Label="TextField Multiline" Multiline="true" />
    </p>
</Panel>

**Comment by limefrogyank** [comment] 2020-05-08 01:19
The  client side demo code has been converted to use the latest dotnetcore bits that include the RC (release candidate) webassembly stuff.  Make sure you have the latest dotnet installed. I don't think the latest VS preview comes with it anymore.

I tested it fairly thoroughly and it seemed to work fine for me.  Make sure you clear the cache...

The live demo on the website is not updated, fyi.

**Comment by limefrogyank** [comment] 2020-05-12 03:50
Hopefully everything is good now... I'm going to close this for now.  Reopen if there are still problems with RichTextEditor

**Closed by limefrogyank** 2020-05-12 03:50 UTC
